package Ordre_de_mission;

import Gestion.*;


import com.itextpdf.text.DocumentException;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ouissam
 */
public class Remplir_Ordre extends javax.swing.JFrame {

    ActionEvent event;
    ResultSet Res, Res1, Res2;
    BD db;

    public String DOTI, destination, motif;

    String prenom, nom;
    int ordre;
    String numero;

    int Numero_ordre, Numero_date;

    String id_Ens;

    String format = "yyyy-MM-dd";
    java.text.SimpleDateFormat formater = new java.text.SimpleDateFormat(format);
    ResultSet Res3;
    String nomP;

    public Remplir_Ordre() {

        db = new BD(Parametre.Host, Parametre.username, Parametre.password, Parametre.IPHOST, Parametre.Port);
        initComponents();

        dest.setEnabled(false);
        motifs.setEnabled(false);

        jAu.setEnabled(false);
        jAu.getDateEditor().setEnabled(false);
        jDu.setEnabled(false);
        jDu.getDateEditor().setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkerboardPainter1 = new org.jdesktop.swingx.painter.CheckerboardPainter();
        checkerboardPainter2 = new org.jdesktop.swingx.painter.CheckerboardPainter();
        jAASLoginService1 = new org.jdesktop.swingx.auth.JAASLoginService();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        text_n = new javax.swing.JTextField();
        dest = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        motifs = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDu = new com.toedter.calendar.JDateChooser();
        jAu = new com.toedter.calendar.JDateChooser();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jLabel14 = new javax.swing.JLabel();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction3 = new org.edisoncor.gui.button.ButtonAction();
        Attes = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(218, 90, 90));
        jLabel1.setText("     Ordre de Mission");

        jLabel6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel6.setText("Destination :");

        jLabel7.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel7.setText("Du:");

        jLabel8.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel8.setText("au:");

        jLabel9.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel9.setText("Motifs:");

        jLabel13.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel13.setText("DOTI : ");

        text_n.setToolTipText("<html><font color=\"blue\"><i>Saisissez votre DOTI</i></font></html>");
        text_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_nMouseClicked(evt);
            }
        });
        text_n.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                text_nComponentRemoved(evt);
            }
        });
        text_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nActionPerformed(evt);
            }
        });
        text_n.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_nKeyPressed(evt);
            }
        });

        motifs.setColumns(20);
        motifs.setRows(5);
        jScrollPane1.setViewportView(motifs);

        jButton3.setBackground(new java.awt.Color(1, 168, 158));
        jButton3.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Vérifier ");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° de Somme", "nom", "prenom", "CIN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText(" Remplissez le formulaire ci dessous svp ");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ressource/logoFso.jpg"))); // NOI18N
        jLabel10.setText("jLabel6");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ressource/back.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        buttonAction1.setText("Afficher Attestation");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });

        buttonAction3.setText("Historique");
        buttonAction3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction3ActionPerformed(evt);
            }
        });

        Attes.setText("Générer Attestation");
        Attes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_n, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jButton3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(299, 299, 299))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(buttonAction3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(Attes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(text_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jAu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAction3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(Attes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DOTI = text_n.getText();

        prenom=null;
        
        Date d = null;

        Object[] data = new Object[4];

        if (DOTI.equals("")) {
            JOptionPane.showMessageDialog(this, "Saisissez le numero de somme svp !!");
        } else {
            Res = db.querySelectAll("Enseignant", "N_somme='"
                    + DOTI + "'");

            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            if(model.getRowCount()==1){
             model.removeRow(0);   
            }
            

            try {
                while (Res.next()) {
                    prenom = Res.getString("prenom");
                    nom = Res.getString("nom");

                    data[0] = Res.getString("N_somme");
                    data[1] = Res.getString("nom");
                    data[2] = Res.getString("prenom");
                    data[3] = Res.getString("CIN");
                    model.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (prenom == null) {
                JOptionPane.showMessageDialog(this, "Le N° de Some est incorrecte");
                text_n.setText("");
                dest.setText("");
                motifs.setText("");
                jDu.setDate(d);
                jAu.setDate(d);

                dest.setEnabled(false);
                motifs.setEnabled(false);

                jAu.setEnabled(false);
                jAu.getDateEditor().setEnabled(false);
                jDu.setEnabled(false);
                jDu.getDateEditor().setEnabled(false);

            } else {
                
                
                dest.setText("");
                motifs.setText("");
                jDu.setDate(d);
                jAu.setDate(d);
                
                dest.setEnabled(true);
                motifs.setEnabled(true);

                jDu.setEnabled(true);
                jDu.getDateEditor().setEnabled(false);

                jAu.setEnabled(true);
                jAu.getDateEditor().setEnabled(false);

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Principale x = new Principale();

        x.setLocationRelativeTo(x.getGlassPane());
        x.setResizable(false);

        x.show();
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void text_nComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_text_nComponentRemoved

    }//GEN-LAST:event_text_nComponentRemoved

    private void text_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_nMouseClicked

    }//GEN-LAST:event_text_nMouseClicked

    private void text_nKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_nKeyPressed
        if (evt.getKeyCode() == 10) {
            jButton3ActionPerformed(event);
        }
    }//GEN-LAST:event_text_nKeyPressed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Principale x = new Principale();

        x.setLocationRelativeTo(x.getGlassPane());
        x.setResizable(false);

        x.show();
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed

        prenom = null;

        DOTI = text_n.getText();
        motif = motifs.getText();
        destination = dest.getText();
        Date date = jAu.getDate();
        Date date1 = jDu.getDate();
        if (DOTI.equals("")) {
            JOptionPane.showMessageDialog(this, "Entrez le N° de Some SVP !!");
        } else {
            Res = db.querySelectAll("Enseignant", "N_somme='" + DOTI + "'");

            try {
                while (Res.next()) {
                    prenom = Res.getString("prenom");

                }
                if (prenom == null) {
                    JOptionPane.showMessageDialog(this, "verifier votre N° de some ");
                } else {
                    if (destination.equals("") || motifs.equals("") || date == null || date1 == null) {

                        if (dest.isEnabled()) {
                            JOptionPane.showMessageDialog(this, "Remplissez tous les champs svp !!");

                        } else {
                            JOptionPane.showMessageDialog(this, "Cliquez sur vérifier pour insérer un nouvel Ordre de Mission ");
                        }
                    } else {
                        Verif_Ordre a = new Verif_Ordre(DOTI, this);
                        a.setLocationRelativeTo(a.getParent());
                        a.setLocationRelativeTo(a.getGlassPane());
                        a.show();
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void buttonAction3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction3ActionPerformed
        try {

            DOTI = text_n.getText();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie , saisissez le N° de somme svp !!!");
        } finally {
            if (text_n.equals("")) {
                JOptionPane.showMessageDialog(this, "saisissez le N° de somme svp !!!");
            } else {
                Res = db.querySelectAll("Enseignant", "N_somme='" + DOTI + "'");

                try {
                    while (Res.next()) {
                        prenom = Res.getString("prenom");

                    }

                    if (prenom == null) {
                        JOptionPane.showMessageDialog(this, "verifier votre N° de somme ");
                    } else {
                        Ordre a = new Ordre(DOTI);
                        a.setLocationRelativeTo(a.getParent());
                        a.show();
                        this.dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAction3ActionPerformed

    private void AttesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttesActionPerformed
        try {
            Date date = jDu.getDate();
            Date date1 = jAu.getDate();
            DOTI = text_n.getText();

            if (dest.equals("") || motifs.equals("") || date == null || date1 == null) {
                JOptionPane.showMessageDialog(this, "Remplissez tous les champs svp !!");
            } else {

                nomP = "" + upperFirst(prenom) + " " + upper(nom);
                if (JOptionPane.showConfirmDialog(null, "êtes vous sûre d'avoir générer l'Attestation de " + nomP + "?") == 0) {

                    Res = db.executionQuery("select count(*) from Ordre_de_mission");
                    Res1 = db.executionQuery("select count(*) from Date");
                    Res2 = db.executionQuery("select id_Enseignant from Enseignant where N_somme='" + DOTI + "'");

                    while (Res2.next()) {

                        id_Ens = Res2.getString("id_Enseignant");

                    }
                    while (Res1.next()) {

                        Numero_date = Integer.parseInt(Res1.getString("count(*)"));

                        Numero_date++;

                    }

                    while (Res.next()) {

                        Numero_ordre = Integer.parseInt(Res.getString("count(*)"));

                        Numero_ordre++;
                        System.out.println(Numero_ordre);
                        ordre = Numero_ordre;
                        String tab[] = {"" + Numero_ordre, dest.getText(), motifs.getText()};
                        db.queryInsert("Ordre_de_mission", tab);

                        String tab1[] = {"" + Numero_date, "" + formater.format(jDu.getDate()), "" + formater.format(jAu.getDate())};
                        db.queryInsert("Date", tab1);

                        String tab2[] = {"" + Numero_ordre, "" + id_Ens, DOTI, "" + Numero_date};
                        db.queryInsert("effectuer", tab2);

                    }

                    Ordre_de_MissionPdf a = new Ordre_de_MissionPdf(DOTI, ordre);

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Remplir_Ordre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AttesActionPerformed

    public Date getDepart() {

        return jAu.getDate();
    }

    public Date getArrivee() {
        return jDu.getDate();
    }

    String upper(String x) {
        return x.toUpperCase();
    }

    String upperFirst(String x) {
        return x.substring(0, 1).toUpperCase() + x.substring(1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction Attes;
    private javax.swing.JTable Table;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction3;
    private org.jdesktop.swingx.painter.CheckerboardPainter checkerboardPainter1;
    private org.jdesktop.swingx.painter.CheckerboardPainter checkerboardPainter2;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JTextField dest;
    private org.jdesktop.swingx.auth.JAASLoginService jAASLoginService1;
    private com.toedter.calendar.JDateChooser jAu;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea motifs;
    private javax.swing.JTextField text_n;
    // End of variables declaration//GEN-END:variables
}
