package Info_perso;


import Gestion.*;
import com.itextpdf.text.Element;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Nv_Enseignant extends javax.swing.JFrame {

    BD db;
    ResultSet Res;
    String DOTI, CIN, NOM, PRENOM, NOMAR, PRENOMAR, DATE, LIEU, SITU, NBR, ADR, EMAIL, ENTREE, RECRU, TEL;
    String filename;

    String format = "yyyy-MM-dd";
    Date e, dn, r;

    java.text.SimpleDateFormat formater = new java.text.SimpleDateFormat(format);

    public Nv_Enseignant() {
        db = new BD(Parametre.Host, Parametre.username, Parametre.password, Parametre.IPHOST, Parametre.Port);
        initComponents();
        
        nomar.setHorizontalAlignment(Element.ALIGN_LEFT);
        prenomar.setHorizontalAlignment(Element.ALIGN_LEFT);

        date.setEnabled(true);
        date.getDateEditor().setEnabled(false);

        entree.setEnabled(true);
        entree.getDateEditor().setEnabled(false);

        recru.setEnabled(true);
        recru.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nbr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lieu = new javax.swing.JTextField();
        adr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        situ = new javax.swing.JTextField();
        img = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nomar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        prenomar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        inserer = new org.edisoncor.gui.button.ButtonAction();
        jLabel14 = new javax.swing.JLabel();
        entree = new com.toedter.calendar.JDateChooser();
        recru = new com.toedter.calendar.JDateChooser();
        date = new com.toedter.calendar.JDateChooser();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 99, 99));
        jLabel2.setText("Fiche d'Informations Personnelles");

        jLabel3.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel3.setText("DOTI:");

        jLabel4.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel4.setText("Nom :");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel5.setText("Prenom :");

        jLabel6.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel6.setText("Situation familiale :");

        jLabel7.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel7.setText("Nombre d'enfants :");

        jLabel8.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel8.setText("Date de naissance:");

        jLabel9.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel9.setText("Lieu :");

        jLabel10.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel10.setText("Adresse  :");

        jLabel11.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel11.setText("E-mail  :");

        jLabel12.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel12.setText("Date de recrutement :");

        jLabel13.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel13.setText("Date d'entrée  :");

        situ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situActionPerformed(evt);
            }
        });

        img.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setToolTipText("Photo de Profil\n");
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel15.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel15.setText("CIN :");

        jLabel16.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel16.setText("الإسم العائلي:");

        jLabel17.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel17.setText("الإسم الشخصي:");

        jLabel1.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel1.setText("GSM :");

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(1, 168, 158));
        jButton3.setText("Parcourir l'Image ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        inserer.setText("Insérer ");
        inserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ressource/back.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)
                        .addGap(94, 94, 94)
                        .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adr, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recru, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(situ, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(119, 119, 119))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(69, 69, 69)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nbr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prenomar)
                            .addComponent(nomar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(inserer, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(54, 54, 54)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(situ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(entree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(recru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(inserer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();//création dun nouveau filechosser
        chooser.setApproveButtonText("Choix du fichier..."); //intitulé du bouton

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            filename = chooser.getSelectedFile().getAbsolutePath().toString();
            ImageIcon icon = new ImageIcon(filename);
            ImageIcon i = new ImageIcon(icon.getImage().getScaledInstance(112, 118, 0));
            img.setIcon(i);
            

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void insererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererActionPerformed
        
        
        String p = null;

        FileInputStream fin = null;
        DOTI = n.getText();

        Res = db.querySelectAll("Enseignant", "N_somme='" + DOTI + "'");

        try {
            while (Res.next()) {
                p = Res.getString("prenom");
            }

            if (p != null) {
                JOptionPane.showMessageDialog(this, "Ce Numéro de SOM existe!!");
            } else {
                try {

                    CIN = cin.getText();
                    NOM = nom.getText();
                     
                      
                    PRENOM = prenom.getText();
                    NOMAR = nomar.getText();
                    PRENOMAR = prenomar.getText();
                    
                   

                    LIEU = lieu.getText();
                    SITU = situ.getText();
                    NBR = nbr.getText();
                    ADR = adr.getText();
                    EMAIL = email.getText();
                    e = entree.getDate();
                    dn = date.getDate();
                    r = recru.getDate();

                    TEL = tel.getText();
                    if (DOTI.equals("") || r == null || e == null || dn == null || CIN.equals("") || NOM.equals("") || PRENOM.equals("") || NOMAR.equals("") || PRENOMAR.equals("")
                            || LIEU.equals("") || SITU.equals("") || NBR.equals("") || ADR.equals("") || EMAIL.equals("")) {
                        JOptionPane.showMessageDialog(this, "vérifiez l'insertion de votre image ou des champs!!");
                    } else {
                        if (JOptionPane.showConfirmDialog(this, "êtes vous sur d'avoir inserer les bonnes informations ?") == 0) {
                            
                            
                            ENTREE = formater.format(e);
                            RECRU = formater.format(r);
                            DATE = formater.format(dn);
                            Res = db.executionQuery("select count(*) from Enseignant");
                            try {
                                while (Res.next()) {

                                    int s = Integer.parseInt(Res.getString("count(*)"));
                                    s++;

                                    if (filename == null) {

                                      
                                        
                                        Connection con = db.connexionDatabase();
                                        PreparedStatement pre = con.prepareStatement("insert into Enseignant "
                                                + "(id_Enseignant,N_somme,CIN,nom,prenom,nom_Ar,prenom_Ar,adresse,Date_naissance,Lieu_Naissance,ad_electronique, "
                                                + "N_telephone,situation_familiale,nb_enfants,date_d_entree,date_recrutement)"
                                                + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                                        pre.setInt(1, s);
                                        pre.setString(2, DOTI);
                                        pre.setString(3, CIN);
                                        pre.setString(4, NOM);
                                        pre.setString(5, PRENOM);
                                        pre.setString(6, NOMAR);
                                        pre.setString(7, PRENOMAR);
                                        pre.setString(8, ADR);
                                        pre.setString(9, DATE);
                                        pre.setString(10, LIEU);
                                        pre.setString(11, EMAIL);
                                        pre.setString(12, TEL);
                                        pre.setString(13, SITU);
                                        pre.setString(14, NBR);
                                        pre.setString(15, ENTREE);
                                        pre.setString(16, RECRU);
                                        pre.executeUpdate();
                                        JOptionPane.showMessageDialog(this, "Vorte insertion est effectuée Avec Succés!!");
                                        Nv_Enseignant_SA x = new Nv_Enseignant_SA(DOTI);
                                        x.setLocationRelativeTo(x.getParent());
                                        x.setLocationRelativeTo(x.getGlassPane());
                                        x.setResizable(false);

                                        x.show();
                                        this.dispose();
                                    } else {
                                        Connection con = db.connexionDatabase();
                                        File imgfile = new File(filename);
                                        fin = new FileInputStream(imgfile);
                                        PreparedStatement pre = con.prepareStatement("insert into Enseignant values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                                        pre.setInt(1, s);
                                        pre.setString(2, DOTI);
                                        pre.setString(3, CIN);
                                        pre.setString(4, NOM);
                                        pre.setString(5, PRENOM);
                                        pre.setString(6, NOMAR);
                                        pre.setString(7, PRENOMAR);
                                        pre.setString(8, ADR);
                                        pre.setString(9, DATE);
                                        pre.setString(10, LIEU);
                                        pre.setString(11, EMAIL);
                                        pre.setString(12, TEL);
                                        pre.setString(13, SITU);
                                        pre.setString(14, NBR);
                                        pre.setString(15, ENTREE);
                                        pre.setString(16, RECRU);
                                        pre.setBinaryStream(17, (InputStream) fin, (int) imgfile.length());
                                        pre.executeUpdate();
                                        JOptionPane.showMessageDialog(this, "Vorte insertion est effectuée Avec Succés!!");
                                        Nv_Enseignant_SA x = new Nv_Enseignant_SA(DOTI);
                                        x.setLocationRelativeTo(x.getParent());
                                        x.setLocationRelativeTo(x.getGlassPane());
                                        x.setResizable(false);

                                        x.show();
                                        this.dispose();
                                    }
                                }
                            } catch (SQLException ex) {
                                Logger.getLogger(Nv_Enseignant.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }

// TODO add your handling code here:
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Nv_Enseignant.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Nv_Enseignant.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_insererActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Principale x = new Principale();

        x.setLocationRelativeTo(x.getGlassPane());
        x.setResizable(false);

        x.show();
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void situActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_situActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTextField cin;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser entree;
    private javax.swing.JLabel img;
    private org.edisoncor.gui.button.ButtonAction inserer;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lieu;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nbr;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomar;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prenomar;
    private com.toedter.calendar.JDateChooser recru;
    private javax.swing.JTextField situ;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
