package Info_perso;

import Gestion.*;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Nv_Enseignant_SA extends javax.swing.JFrame {

    BD db;
    ResultSet Res, Res1, Res2;

    String numero;
    String prenom;
    String cadre;
    int id_cadre;
    String grade;
    String echelon;
    Date anciennete, anciennete1;

    String echelon_T;
    int Numero_situation;
    String type;

    String format = "yyyy/MM/dd";
    java.text.SimpleDateFormat formater = new java.text.SimpleDateFormat(format);
    private String cadre_T;
    private String grade_T;
    private ActionEvent event;
    private String fonc;
    private String depar;

    /**
     * Creates new form Nv_Enseignant_SA
     */
    public Nv_Enseignant_SA(String num) {
        db = new BD(Parametre.Host, Parametre.username, Parametre.password, Parametre.IPHOST, Parametre.Port);

        initComponents();
        this.numero = num;
        
        doti.setText(numero);
        doti.setEnabled(false);
        fonction.setText("Enseignant-chercheur");
        fonction.setEnabled(false);

        text_anciennete.setEnabled(true);
        text_anciennete.getDateEditor().setEnabled(false);
        text_anciennete1.setEnabled(true);
        text_anciennete1.getDateEditor().setEnabled(false);

        cadre = ComboCadre.getSelectedItem().toString();
        grade = ComboGrade.getSelectedItem().toString();
        type = ComboEchelon.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_anciennete = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboCadre = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ComboGrade = new javax.swing.JComboBox();
        ComboEchelon = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        text_anciennete1 = new com.toedter.calendar.JDateChooser();
        inserer = new org.edisoncor.gui.button.ButtonAction();
        jLabel2 = new javax.swing.JLabel();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jLabel9 = new javax.swing.JLabel();
        doti = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fonction = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel4.setText("Grade :");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel5.setText("Cadre :");

        jLabel6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel6.setText("Echelon :");

        ComboCadre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professeur assistant", "Professeur habilité", "Professeur d Enseignement Supérieur" }));
        ComboCadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCadreActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel7.setText("Ancienneté de l'echelon :");

        ComboGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        ComboGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGradeActionPerformed(evt);
            }
        });

        ComboEchelon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        ComboEchelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEchelonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel8.setText("Ancienneté du grade:");

        inserer.setText("Insérer");
        inserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 99, 99));
        jLabel2.setText("Situation Administrative");

        jLabel9.setFont(new java.awt.Font("Serif", 3, 15)); // NOI18N
        jLabel9.setText("DOTI:");

        jLabel10.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel10.setText("Département:");

        jLabel11.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel11.setText("Fonction:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboCadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboEchelon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(doti, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fonction, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_anciennete1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(text_anciennete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inserer, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(clockFace1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ComboEchelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_anciennete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_anciennete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addComponent(inserer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCadreActionPerformed
        cadre = ComboCadre.getSelectedItem().toString();
        if (cadre.equalsIgnoreCase("Professeur assistant") || cadre.equalsIgnoreCase("Professeur habilité")) {
            if (ComboGrade.getItemCount() == 3) {
                ComboGrade.addItem("D");
            }
        } else {

            if (ComboGrade.getItemCount() == 4) {
                ComboGrade.removeItemAt(3);
            }

        }
    }//GEN-LAST:event_ComboCadreActionPerformed

    private void ComboGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGradeActionPerformed
        grade = ComboGrade.getSelectedItem().toString();

        if (cadre.equalsIgnoreCase("Professeur assistant") || cadre.equalsIgnoreCase("Professeur habilité")) {
            if (ComboEchelon.getItemCount() == 5) {
                ComboEchelon.removeItemAt(4);

            }
        } else {
            if (ComboEchelon.getItemCount() == 4) {
                ComboEchelon.addItem("5");
            }
        }
    }//GEN-LAST:event_ComboGradeActionPerformed

    private void ComboEchelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEchelonActionPerformed
        echelon = ComboEchelon.getSelectedItem().toString();
    }//GEN-LAST:event_ComboEchelonActionPerformed

    private void insererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererActionPerformed

        anciennete = text_anciennete.getDate();
        anciennete1 = text_anciennete1.getDate();

        fonc = fonction.getText();
        depar = dep.getText();

        if (cadre.equals("Professeur assistant")) {
            id_cadre = 1;
        }
        if (cadre.equals("Professeur habilité")) {
            id_cadre = 2;
        }
        if (cadre.equals("Professeur d Enseignement Supérieur")) {
            id_cadre = 3;
        }

        if (depar.equals("") || fonc.equals("") || anciennete == null || anciennete1 == null) {
            JOptionPane.showMessageDialog(this, "Remplissez tous les champs svp !!!");
        } else {

            Res = db.querySelectAll("Enseignant", "N_somme='" + numero + "'");
            Res1 = db.executionQuery("select count(*) from situation_administrative ");

            try {
                while (Res1.next()) {

                    Numero_situation = Integer.parseInt(Res1.getString("count(*)"));

                    Numero_situation++;

                    System.out.print(Numero_situation);
                }

                while (Res.next()) {

                    if (JOptionPane.showConfirmDialog(null, "êtes vous sûre d'avoir inserer les bonnes options ??") == 0) {
                        System.out.println("zz");
                        String tab[] = {"" + Numero_situation, grade, echelon, formater.format(anciennete), formater.format(anciennete1),fonc, depar, "" + id_cadre};
                        db.queryInsert("situation_administrative", tab);

                        String tab1[] = {"" + Numero_situation, "" + Res.getString("id_Enseignant"), "" + numero};
                        db.queryInsert("avoir", tab1);
                        JOptionPane.showMessageDialog(this, "Vorte insertion est effectuée Avec Succés!!");
                        Nv_Enseignant_D x = new Nv_Enseignant_D(numero);
                        x.setLocationRelativeTo(x.getParent());
                        x.setLocationRelativeTo(x.getGlassPane());
                        x.setResizable(false);

                        x.show();
                        this.dispose();
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_insererActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboCadre;
    private javax.swing.JComboBox ComboEchelon;
    private javax.swing.JComboBox ComboGrade;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JTextField dep;
    private javax.swing.JTextField doti;
    private javax.swing.JTextField fonction;
    private org.edisoncor.gui.button.ButtonAction inserer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser text_anciennete;
    private com.toedter.calendar.JDateChooser text_anciennete1;
    // End of variables declaration//GEN-END:variables
}
